import Foundation

/// Curated, local vocabulary packs that users can opt into for Parakeet recognition.
/// Each preset contains 25 terms. Enabling every pack plus the three required
/// brand terms stays within FluidAudio's 256-term vocabulary limit. User-managed
/// words have higher weights and take priority whenever the runtime cap is reached.
struct VocabularyPreset: Identifiable, Hashable, Sendable {
    let id: String
    let title: String
    let description: String
    let systemImage: String
    let terms: [ParakeetVocabularyStore.VocabularyConfig.Term]
}

enum VocabularyPresetCatalog {
    typealias Term = ParakeetVocabularyStore.VocabularyConfig.Term

    static let all: [VocabularyPreset] = [
        VocabularyPreset(
            id: "artificial-intelligence",
            title: "AI & Data",
            description: "Models, prompts, training, and modern AI tools",
            systemImage: "brain.head.profile",
            terms: VocabularyPresetCatalog.makeTerms([
                "AI",
                "agentic AI",
                "artificial intelligence",
                "computer vision",
                "deep learning",
                "foundation model",
                "machine learning",
                "large language model",
                "LLM",
                "generative AI",
                "neural network",
                "transformer",
                "inference",
                "fine-tuning",
                "tokenization",
                "embedding",
                "vector database",
                "retrieval-augmented generation",
                "RAG",
                "prompt engineering",
                "multimodal",
                "natural language processing",
                "hallucination",
                "ChatGPT",
                "OpenAI",
            ])
        ),
        VocabularyPreset(
            id: "law",
            title: "Law",
            description: "Litigation, procedure, and legal practice",
            systemImage: "scale.3d",
            terms: VocabularyPresetCatalog.makeTerms([
                "affidavit",
                "amicus curiae",
                "appellant",
                "appellee",
                "arbitration",
                "attorney-client privilege",
                "burden of proof",
                "case law",
                "deposition",
                "defendant",
                "discovery",
                "due diligence",
                "fiduciary",
                "habeas corpus",
                "injunction",
                "jurisdiction",
                "litigation",
                "memorandum",
                "motion to dismiss",
                "plaintiff",
                "precedent",
                "statute of limitations",
                "subpoena",
                "summary judgment",
                "voir dire",
            ])
        ),
        VocabularyPreset(
            id: "accounting",
            title: "Accounting",
            description: "Financial statements, close, audit, and tax",
            systemImage: "sum",
            terms: VocabularyPresetCatalog.makeTerms([
                "accounts payable",
                "accounts receivable",
                "accrual",
                "adjusting entry",
                "amortization",
                "audit trail",
                "balance sheet",
                "cash flow statement",
                "chart of accounts",
                "cost of goods sold",
                "CPA",
                "current assets",
                "deferred revenue",
                "depreciation",
                "double-entry accounting",
                "GAAP",
                "general ledger",
                "internal controls",
                "journal entry",
                "materiality",
                "reconciliation",
                "retained earnings",
                "revenue recognition",
                "trial balance",
                "year-end close",
            ])
        ),
        VocabularyPreset(
            id: "finance",
            title: "Finance",
            description: "Corporate finance, valuation, and reporting",
            systemImage: "chart.line.uptrend.xyaxis",
            terms: VocabularyPresetCatalog.makeTerms([
                "basis point",
                "bond yield",
                "capital expenditure",
                "capital structure",
                "cash flow",
                "compound interest",
                "cost of capital",
                "credit spread",
                "debt service",
                "debt-to-equity ratio",
                "discounted cash flow",
                "EBITDA",
                "enterprise value",
                "fiscal year",
                "free cash flow",
                "gross margin",
                "interest rate",
                "leverage",
                "liquidity",
                "net present value",
                "operating margin",
                "return on equity",
                "terminal value",
                "WACC",
                "working capital",
            ])
        ),
        VocabularyPreset(
            id: "investment",
            title: "Investment",
            description: "Markets, portfolios, funds, and deal terms",
            systemImage: "briefcase.fill",
            terms: VocabularyPresetCatalog.makeTerms([
                "alpha",
                "asset allocation",
                "asset class",
                "benchmark",
                "beta",
                "capital call",
                "capital gain",
                "carried interest",
                "diversification",
                "dividend yield",
                "dollar-cost averaging",
                "ETF",
                "exchange-traded fund",
                "hedge fund",
                "index fund",
                "internal rate of return",
                "limited partner",
                "net asset value",
                "portfolio company",
                "private equity",
                "risk-adjusted return",
                "Sharpe ratio",
                "term sheet",
                "venture capital",
                "yield curve",
            ])
        ),
        VocabularyPreset(
            id: "art",
            title: "Art & Design",
            description: "Studio practice, criticism, and visual design",
            systemImage: "paintpalette.fill",
            terms: VocabularyPresetCatalog.makeTerms([
                "avant-garde",
                "art direction",
                "chiaroscuro",
                "color theory",
                "composition",
                "conceptual art",
                "contemporary art",
                "curatorial",
                "diptych",
                "expressionism",
                "impressionism",
                "installation art",
                "minimalism",
                "mixed media",
                "negative space",
                "palette",
                "perspective",
                "plein air",
                "provenance",
                "sculpture",
                "surrealism",
                "triptych",
                "trompe-l'oeil",
                "typography",
                "visual hierarchy",
            ])
        ),
        VocabularyPreset(
            id: "politics",
            title: "Politics",
            description: "Government, elections, legislation, and policy",
            systemImage: "building.columns.fill",
            terms: VocabularyPresetCatalog.makeTerms([
                "bipartisan",
                "ballot measure",
                "campaign finance",
                "caucus",
                "constituency",
                "electoral college",
                "executive order",
                "filibuster",
                "gerrymandering",
                "incumbent",
                "legislation",
                "legislature",
                "lobbying",
                "parliamentary",
                "plurality",
                "political action committee",
                "polling",
                "primary election",
                "public policy",
                "proportional representation",
                "redistricting",
                "referendum",
                "separation of powers",
                "super PAC",
                "voter turnout",
            ])
        ),
        VocabularyPreset(
            id: "journalism",
            title: "Journalism",
            description: "Reporting, editing, publishing, and newsrooms",
            systemImage: "newspaper.fill",
            terms: VocabularyPresetCatalog.makeTerms([
                "attribution",
                "breaking news",
                "byline",
                "conflict of interest",
                "copy editor",
                "correction",
                "dateline",
                "editorial",
                "embargo",
                "fact-checking",
                "feature story",
                "freelance journalist",
                "headline",
                "investigative journalism",
                "lede",
                "masthead",
                "news desk",
                "nut graf",
                "off the record",
                "op-ed",
                "press release",
                "source verification",
                "style guide",
                "watchdog journalism",
                "wire service",
            ])
        ),
        VocabularyPreset(
            id: "software",
            title: "Software",
            description: "Engineering, code review, systems, and delivery",
            systemImage: "chevron.left.forwardslash.chevron.right",
            terms: VocabularyPresetCatalog.makeTerms([
                "API",
                "algorithm",
                "backend",
                "CI/CD",
                "codebase",
                "continuous integration",
                "containerization",
                "database migration",
                "dependency",
                "deployment",
                "frontend",
                "GitHub",
                "Kubernetes",
                "latency",
                "microservice",
                "observability",
                "pull request",
                "refactoring",
                "repository",
                "runtime",
                "SDK",
                "source control",
                "technical debt",
                "unit test",
                "version control",
            ])
        ),
        VocabularyPreset(
            id: "cybersecurity",
            title: "Cybersecurity",
            description: "Identity, threats, defense, and security testing",
            systemImage: "lock.shield.fill",
            terms: VocabularyPresetCatalog.makeTerms([
                "authentication",
                "authorization",
                "attack surface",
                "ciphertext",
                "credential stuffing",
                "cryptography",
                "CVE",
                "cybersecurity",
                "DDoS",
                "endpoint detection and response",
                "encryption",
                "firewall",
                "intrusion detection system",
                "least privilege",
                "malware",
                "multi-factor authentication",
                "penetration testing",
                "phishing",
                "ransomware",
                "security information and event management",
                "security operations center",
                "social engineering",
                "threat actor",
                "zero-day vulnerability",
                "zero trust",
            ])
        ),
    ]

    static let allIDs = Set(VocabularyPresetCatalog.all.map(\.id))

    static func normalizedIDs<S: Sequence>(_ ids: S) -> Set<String> where S.Element == String {
        Set(ids).intersection(self.allIDs)
    }

    static func presets(for ids: Set<String>) -> [VocabularyPreset] {
        let normalized = self.normalizedIDs(ids)
        return self.all.filter { normalized.contains($0.id) }
    }

    static func terms(for ids: Set<String>) -> [Term] {
        self.presets(for: ids).flatMap(\.terms)
    }

    private static func makeTerms(_ values: [String]) -> [Term] {
        values.map { Term(text: $0, weight: 5.5) }
    }
}
